Resources:
  ThreatalyticsPlansTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ThreatalyticsPlans
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ThreatalyticsPaymentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ThreatalyticsPayments
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: payment_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: payment_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserPaymentsIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL